<?php


    CONST ESTADO_CREACION_EXITOSA = 1;
    CONST ESTADO_CREACION_FALLIDA = 2;
    CONST ESTADO_ERROR_BD = 3;
    CONST ESTADO_AUSENCIA_CLAVE_API = 4;
    CONST ESTADO_CLAVE_NO_AUTORIZADA = 5;
    CONST ESTADO_FALLA_DESCONOCIDA = 6;
    CONST ESTADO_PARAMETROS_INCORRECTOS = 7;
    CONST ESTADO_ERROR_DE_PAGINACION = 8;
    CONST ESTADO_PETICION_NO_EXISTE = 9;
    //constantes de inicio
    CONST ESTADO_URL_INCORRECTA = 10;// codigo de url incorrecta
    CONST ESTADO_EXISTENCIA_RECURSO = 11;
    CONST ESTADO_METODO_NO_PERMITIDO = 12;


?>